#-------------------------------------------#
# J. Michael Beaver                         #
# 16 June 2015                              #
#-------------------------------------------#
# No attempt has been made to optimize this #
# code. There may be no error-checking.     #
#-------------------------------------------#
# http://rosalind.info/problems/rna/        #
#-------------------------------------------#

t = "ACGCCACATCCTCGTTCGCGCAGCGTCATCGTTCCGCAATCTCACGAGGGATGGCATGCAATCACAGGCAGGAATGTGGTTGAAGGATTATACTGCAATCTATCTAATCCGAGAGTCGCACTGTTCGCGGCGTTCCGCTGAGTTCGCACATCGCGGCGTTAAGCGACTCCCCCAATTTAAAGTCATAAGTCCTAGTCTACCCCTCATTTCGACTTTAAGTTTTTGGCTAGCATATCTTTCAGAAGCCGGAGCAACCCTCGAGGTCACGGGCGTCTTGATTATGCCGATACGGCACGGGCCCAGGGACCGAATTCCCTATAGCTGTTACCTCGTCTCAGGCCCCTGTAAAGTTAACTGTCGTCGGTACGTCAGGACAGTGAGCGTCGCAATCCGGTGTGGTTGGGGCGGGCACTGAACCGACTGGAGTCCAAACGCGTAACTCGCAGGAATGCAATAAAAGAGGGGAATCTCCACACTTTCCTCTTTTAGCAATGTAAACCTTACCACCACATAACCGCTAGGGGTAACCGGATAATTGGTCCAATCCGTCTGTTACGCACTGTATACCAAGTAGAAGTACGTGGCGGTTGCTGTCCGATCAGTAGCCCGAGATTACGACGTCCTTGCGTTGACGCGGTTTGGACCTCCCAGAGGGGTCCAAAGCTTGGTGATTGGCTACGGGCTGAGTATGTTGGATCTATTGACCAGATTAGTCAACTGCGATTAGTTGCGTGACCCCCGCGACTCGCCCTACAAATTGACGCGGAATTTTGTATAGATTCATGCATATCCAACCTCTGGACCTGTGAGAATGTGCTTGCGTCGTGAAGCCAGGTTACTCTTTTATTGTGATGGTTCAGCTATAAATGCTCCTCCTCCAACTTGTTAACCTAGCTCCAATTATGAGTATAGCGAAAACGGA"

print(t.replace('T', 'U'))
