#-------------------------------------------#
# J. Michael Beaver                         #
# 17 June 2015                              #
#-------------------------------------------#
# No attempt has been made to optimize this #
# code. There may be no error-checking.     #
#-------------------------------------------#
# http://rosalind.info/problems/subs/       #
#-------------------------------------------#

s = "ACGACGAGGCTCGAGGCTTCCGAGGCTGCGAGGCTCGAGGCTGTTGCCATCCGAGGCTACCGCGAGGCTACCGAGGCTTCGAGGCTACCGAGGCTGTATCGAGGCTCACCGAGGCTCGAGGCTTGGGAAGAATACGAGGCTGACGAGGCTGCGAGGCTTCGAGGCTTCGCGAGGCTTCGAGGCTCCCGAGGCTCCGAGGCTCGAGGCTCCGGCGCGAGGCTCGAGGCTCGAGGCTTCTTCCGAGGCTTCGAGGCTCGAGGCTACGAGGCTAGCGAGGCTCGAGGCTCCGAGGCTACGAGGCTCCGAGGCTTTTCGAGGCTCGAGGCTACGAGGCTTATTCACCACTAGCGAGGCTCCGAGGCTATGGGTTGCGAGGCTCGAGGCTGCGCGAGGCTTCGAGGCTATGCGAGGCTTGGGCGAGGCTCGAGGCTCGAGGCTGACGAGGCTGACGAGGCTACGAGGCTCGAGGCTCCACGAGGCTCGATCCGAGGCTGACGAGGCTGACGAGGCTCCCGAGGCTGTGCGAGGCTCGAGGCTACGAGGCTCTTCGAGGCTGGCAGGCGAGGCTAGCGATAACGAGGCTCGCACGAGGCTCCGAGGCTGGCCGAGGCTCGAGGCTCGAGGCTCACGAGGCTTTCGAGGCTGCGAGGCTCCCCTTACCCGAGGCTCGAGGCTTTGGGCGCTCGAGGCTTCGAGGCTCAGCGAGGCTGCGGCCGAGGCTGGTCAACGAGGCTCCGAGGCTTCGAGGCTCGAGGCTTTGTTGCGAGGCTCGAGGCTCGAGGCTTCGAGGCTGGGACGGACACCGTCGAGGCTCGACGAGGCTTGACGAGGCTCTCCGAGGCTGTCGAGGCTCGAGGCTCGAGGCTATCGAGGCTCCTTTGGGGACCAATCCGAGGCTCGAGGCTCAAGAAGCGAGGCTTCGAGGCTGGACCGAGGCTCGAGGCTCGAGGCT"
t = "CGAGGCTCG"
szS = len(s)
szT = len(t)

for i in range(0, szS):
    x = s[i:i+szT]
    if (x == t):
        print(i + 1, end=' ')
